model:
  model_name: "causal_aspire_dropout"
  reg_lambda: 100.0
  alpha: 0.5 # 2nd-order energy normalization strength
  gamma: 0.5 # Causal regularization strength
  dropout_p: 0.3 # Dropout probability
