model_name: "dr_jl"

model:
  name: "dr_jl"
  embed_dim: 64
  reg_weight: 0.001
  gamma: 0.5           # Propensity exponent
  eta: 1.0             # Weight for the imputation error compensation (Standard: 1.0)

train:
  epochs: 100
  batch_size: 4096
  lr: 0.001
  weight_decay: 1e-5
  optimizer: "Adam"
  patience: 10
  loss_type: "pairwise"
  num_negatives: 1
  negative_sampling_strategy: "uniform"
