# Global Evaluation Default Configuration
method: "full" # full, sampled, uni99
top_k: [10, 20, 50]
metrics:
  ["Recall", "NDCG", "HitRate", "Precision", "Coverage", "Novelty", "GiniIndex"]
main_metric: "NDCG"
main_metric_k: 20
long_tail_percent: 0.8
